local Eggs = {
	{
		id = "egg_1",
		name = "Coral Egg",
		price = 10_000,
		rarity = "Common",
		color = Color3.fromRGB(255, 166, 122),
	},
	{
		id = "egg_2",
		name = "Current Egg",
		price = 20_000,
		rarity = "Uncommon",
		color = Color3.fromRGB(116, 206, 255),
	},
	{
		id = "egg_3",
		name = "Reef Egg",
		price = 30_000,
		rarity = "Rare",
		color = Color3.fromRGB(108, 255, 182),
	},
	{
		id = "egg_4",
		name = "Abyss Egg",
		price = 40_000,
		rarity = "Epic",
		color = Color3.fromRGB(143, 126, 255),
	},
	{
		id = "egg_5",
		name = "Leviathan Egg",
		price = 50_000,
		rarity = "Legendary",
		color = Color3.fromRGB(255, 214, 84),
	},
}

return Eggs
